### ISSUE TITLE
font not accessible through @font-face in the footer

### ISSUE THREAD

**Issue by mayarichman** [youngist/clean-blog#44]

**Comment by mayarichman** [comment]
Solved. Closing.

``` css
@font-face {
    font-family: 'engel_light_ltdlight';
    src: url('engellight_ltd-webfont.eot');
    src: url('engellight_ltd-webfont.eot?#iefix') format('embedded-opentype'),
         url('engellight_ltd-webfont.woff') format('woff'),
         url('engellight_ltd-webfont.ttf') format('truetype'),
         url('engellight_ltd-webfont.svg#engel_light_ltdlight') format('svg');
    font-weight: normal;
    font-style: normal;

}
```
